replicaCount: 1

image:
  repository: ashiqa/ashiq-ar-devops-workflow-practice-frontend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

# Set to true to create an OpenShift Route
isOpenShift: true

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
