{{- if .Values.isOpenShift }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "backend.fullname" . }}
    weight: 100
  port:
    targetPort: http-notesapp-backend
{{- end }}
