apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-db
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_HOST: {{ .Values.postgres.host | quote }}
  POSTGRES_PORT: {{ .Values.postgres.port | quote }}
  POSTGRES_DB: {{ .Values.postgres.db | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
